version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - FLASK_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgresql-database-hgwks4o884cgo8wo8ok84ock:K8A1EuplrcGvVwi577BihGvTkKXbWhe6WDA5OJY6sE7XGd4GXCmdaeUTNddPpNRl@postgresql-database-hgwks4o884cgo8wo8ok84ock:5432/postgresql-database-hgwks4o884cgo8wo8ok84ock
      - SETUP_ADMIN_EMAIL=gab.duano101898@gmail.com
      - SETUP_ADMIN_PASSWORD=Gabriel_101898@@