version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - FLASK_ENV=production
      - PORT=3001
    command: ["npm", "start"]