version: '3.8'

services:
  # Frontend development service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: beacon-blast-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001
    networks:
      - beacon-blast-network
    command: npm run dev -- --host

  # Backend development service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: beacon-blast-backend-dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - backend-data:/app/instance
      - backend-uploads:/app/uploads
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - START_SCHEDULER=true
      - PORT=5001
    networks:
      - beacon-blast-network
    command: python app.py

volumes:
  backend-data:
  backend-uploads:

networks:
  beacon-blast-network:
    driver: bridge
