[start]
cmd = "npm start"

[phases.setup]
nixPkgs = ["python310", "nodejs_20", "python310Packages.pip"]

[phases.install]
cmd = "npm ci && cd backend && pip install -r requirements.txt && cd .."

[phases.build]
cmd = "npm run build"

[variables]
NODE_ENV = "production"
FLASK_ENV = "production"
PORT = "3000"