# Nixpacks configuration for Beacon Blast Email Platform
# Explicitly configure Node.js build with Python runtime

providers = ["node"]

[variables]
NODE_ENV = "production"
FLASK_ENV = "production"
PORT = "5001"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.build]
cmds = [
    "npm --version",
    "node --version", 
    "npm ci",
    "npm run build",
    "python3 --version",
    "pip3 install --no-cache-dir -r backend/requirements.txt"
]

[phases.start] 
cmd = "cd backend && python3 app.py"