# Nixpacks configuration for Beacon Blast Email Platform
# Explicitly configure Node.js and Python setup

[variables]
NODE_ENV = "production" 
FLASK_ENV = "production"
PORT = "3000"
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.build]
cmds = [
    "python3 --version",
    "pip3 install --no-cache-dir -r backend/requirements.txt"
]

[start]
cmd = "chmod +x /app/start.sh && /app/start.sh"