[start]
cmd = "npm start"

[phases.setup]
nixPkgs = ["python310", "nodejs_20", "python310Packages.pip", "curl", "wget"]

[phases.install]
cmd = "npm ci && cd backend && pip install -r requirements.txt && cd .."

[phases.build] 
cmd = "npm run build"

[phases.postBuild]
cmd = "echo '🎯 Running initial admin setup...' && python3 setup_admin.py || echo '⚠️ Admin setup failed or already completed'"

[variables]
NODE_ENV = "production"
FLASK_ENV = "production"
PORT = "3000"
NIXPACKS_NO_SPA_FALLBACK = "1"
NIXPACKS_BUILD_CMD = "npm run build"
SECRET_KEY = "beacon-blast-secret-key-change-in-production"
JWT_SECRET_KEY = "beacon-blast-jwt-secret-change-too"