"""Add notifications table

Revision ID: 9280cb5c7e10
Revises: fde3a360206b
Create Date: 2025-10-30 21:03:57.484315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9280cb5c7e10'
down_revision = 'fde3a360206b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create notifications table
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CAMPAIGN_CREATED', 'CAMPAIGN_SUCCESS', 'CAMPAIGN_FAILED', 'CAMPAIGN_DRAFT', 'CAMPAIGN_SCHEDULED', 'CAMPAIGN_SENDING', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_campaigns_smtp_account_id', 'smtp_accounts', ['smtp_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_smtp_account_id', type_='foreignkey')
    
    op.drop_table('notifications')

    # ### end Alembic commands ###
