"""Add SMTP account multi-user system with assignments

Revision ID: fde3a360206b
Revises: 322f2dd793be
Create Date: 2025-10-30 16:47:41.903668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde3a360206b'
down_revision = '322f2dd793be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create smtp_accounts table
    op.create_table('smtp_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('host', sa.String(length=255), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=500), nullable=False),
        sa.Column('encryption', sa.String(length=20), nullable=True),
        sa.Column('from_name', sa.String(length=100), nullable=False),
        sa.Column('from_email', sa.String(length=255), nullable=False),
        sa.Column('reply_to_email', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('last_tested_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('daily_limit', sa.Integer(), nullable=True),
        sa.Column('emails_sent_today', sa.Integer(), nullable=True),
        sa.Column('total_emails_sent', sa.Integer(), nullable=True),
        sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create user_smtp_assignments junction table
    op.create_table('user_smtp_assignments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('smtp_account_id', sa.Integer(), nullable=False),
        sa.Column('assigned_by_admin_id', sa.Integer(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by_admin_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['smtp_account_id'], ['smtp_accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'smtp_account_id', name='unique_user_smtp_assignment')
    )
    
    # Add smtp_account_id to campaigns table
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_campaigns_smtp_account', 'smtp_accounts', ['smtp_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove smtp_account_id from campaigns
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_smtp_account', type_='foreignkey')
        batch_op.drop_column('smtp_account_id')
    
    # Drop user_smtp_assignments table
    op.drop_table('user_smtp_assignments')
    
    # Drop smtp_accounts table
    op.drop_table('smtp_accounts')

    # ### end Alembic commands ###
