name: Docker Build Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Docker image
        if: matrix.service == 'frontend'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: beacon-blast-frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Backend Docker image
        if: matrix.service == 'backend'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: beacon-blast-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          if [ "${{ matrix.service }}" == "frontend" ]; then
            docker run --rm beacon-blast-frontend:test nginx -t
          else
            docker run --rm beacon-blast-backend:test python -c "import app; print('Backend imports successful')"
          fi
